### ISSUE TITLE
issue while patching

### ISSUE THREAD

**Issue by vornthorn** [Ich73/TranslationToolkit#1]
hey there thanks for the amazing tool,

just I am having issues while trying to patch v 2.1 of DQMT I am getting this error,

"
~ Game File ~
The full path to the CIA or 3DS file to extract.
Enter game file [DQMT.cia]:
>> DQMT.cia

~ Game Folder ~
The full path to the folder the game should be extracted to.
Enter game folder [cia-game]:
>> cia-game

Game File: DQMT.cia
Game Folder: cia-game

Start script? [y/n] y

Extracting Step 1/7
invalid literal for int() with base 10: 'xeFS'
ERROR: Extracting Failed
"

**Comment by Ich73** [comment]
Hey, first of all, I moved the issue because the console output you posted was from the tool [Translation Toolkit](https://github.com/Ich73/TranslationToolkit) and not [Game Patcher](https://github.com/Ich73/GamePatcher) where you originally posted the issue.

However, I would recommend to use Game Patcher if you only want to patch the game and play it (and not work on a translation yourself). To do so follow these instructions: [DQMT/Wiki/Installing-Releases](https://github.com/Ich73/DQMT-FanTranslation/wiki/Installing-Releases).

But to address the issue you posted: Make sure to delete the game folder (i.e., `cia-game`) before running the script, and then try to extract the game again. If it doesn't work, please take a screenshot of the contents of the `cia-game` folder after the script has failed and I will try to help further.
